### ISSUE TITLE
Mentors for new project members

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/AgileVentures#2]
As a new member of a project
In order to get up to speed with the project 
And to be confident in my first few  PR's
I would like someone to act as a mentor/guide in the early days of my membership of that project

Rationale.
I think it is easy to forget that it can be a lot of firsts for someone joining AV.
- First time using ruby in a "real" project
- First time in a remote team
- First time using github forks and branches
- First time having anything to do with this particular project

and it can be a bit of a struggle to get going.  Yes we welcome people in #new_members and tell them where to go to join a project...but then what?  And what if you post a message but nobody answers?  Do you post again later and maybe get chastised for having posted it the previous day?  Do you struggle on alone?

Once you get past that hurdle, you've found an issue to work on, do it, and are now submit a PR
Turns out that even though you set up your github as best you could (or perhaps the project lacked instructions on "this is how we work with github" so you never knew what to do) but you've accidentally included changes from another PR or don't have all the up to date develop branch code or cloned master instead of develop - any number of things may have gone wrong.

Then add in the fact that you don't know the unwritten rules of this project that you need to use single instead of double quotes or you should always add a test or you should/should not comment your code or other such n00b mistakes.

It could be incredibly intimidating and off putting to have members of the team, however well meaning, descend on your PR and offer nothing but criticism of it instead of recognising that this person is new and doesn't necessarily know all the ins and outs of the project and therefore should be given a bit of leeway and encouragement and advice.

I think having a mentor would be help enormously with all of this - someone from the existing team who volunteers to be the "goto" person for the new member for the first few weeks. 
They would help them get the project up and running and the new member could submit a PR to their mentor's repo so they can review it together and get it ready for submission to the main project repo.
I believe this would help foster a spirit of friendliness and cooperation and give new members much more confidence in what they are doing going forward - having a named "friendly face" to go to seems far more inviting than what, to the newbie is an anonymous bunch of people they know nothing about.

**Comment by tansaku** [comment]
I think this is a great idea @freeranger and I'm happy to trial this by being your mentor in the first instance.

I think the difficulty that we might have is with getting people to commit to be mentors, but that's not a reason to try it.  Let's you and me try it and work out something more concrete perhaps?

In general in AV everybody is supposed to be a mentor to the new people coming onboard, but having a specific go to person makes sense.

I'm always pushing people to ask questions in group channels and forums, but I am realising more and more that is very intimidating for many people.   The flip side is that it's really hard for a volunteer organisation to operate if all these discussions are happening in 1-1 chats.

Asking somebody in 121 basically means that you have to wait for them to respond - and you are also putting special pressure on them to help you.  I'm always telling students and mentees to ask in group chats and forums to minimize the time before they receive help.   For me personally I say who cares what others think?  I'm going to ask my question and if I look foolish who cares :-)

But I see we need to meet people in the middle.   So hopefully some sort of mentor program might help people feel more confident so that they can ultimately operate confidently in group fora.

**Comment by freeranger** [comment]
I would see being a mentor as something you volunteer for when someone new arrives.
Ideally joey new dev rocks up to the project channel, introduces themselves, and someone - anyone - could be the last man in or could be the longest serving member - volunteers to help them through the early days.

This doesn't preclude asking questions in slack, but what happens when you ask a question and nobody replies?
Do you post it again another day (and risk being admonished for already posting that) or do you continue to struggle?
Perhaps the "workflow" is:

1. try to solve your problem yourself (but don't spend days on it).
2. Ask in the appropriate channel (or skip to step 3 if there are reasons not to ask there)
3. If no joy, ask your mentor and wait patiently for a response

Some problems I have encountered as a newbie with asking in slack are:
- Getting told to ask the question somewhere else
- Getting told not to ask that question
- Getting told your question is too long
- Not getting any response at all.

All of the above are pretty off-putting.

The mentors role I would not see as being particularly long lived and would be along the lines of:
- Helping them to get up and running with the project locally - this could just be pointing them to existing useful docs
- Helping to choose "good" issues for newbies to work on
- Maybe some guidance working on those early issues - could be offers to pair, helpful suggestions, talking through a problem
- Reviewing their PR (maybe the PR is against the mentors repo?) before it goes for general review by the team
- Helping them craft issues/slack posts so they get the message across as succinctly as possible

I don't see this lasting longer than a couple of weeks or a couple of PR's, though obviously it depends on the individuals involved.
