### ISSUE TITLE
incorrect linkage between AV premium pages and those in this repo

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/AgileVentures#57]
I note we're still a bit screwed up in that #websiteone is linking to premium mob and f2f pages with underscores (to pages that have the correct open/close HTML formatting) and that the pages PREMIUM_MOB.md and PREMIUM_F2F.md in the AV/AV repo are being copied over to premium-mob and premium-f2f (i.e. with hyphens) so updates there are not coming through to the actual pages that are linked into the site, and also those pages in AV/AV don't have the correct open/close HTML ...

**Comment by mattwr18** [comment]
@tansaku Peter and I started working on this issue on Saturday, but it was difficult to make sense of what exactly the issue is.

 It seems like to us that in the first place we want the url to use slugs with hyphens like premium-mob while they are using underscores as you stated above. 

We saw that there is a rake task that fetches the static_pages, and we are going to drop in pry to poke around that to get a better idea of what is coming in, but we were trying to get a grasp for the lifecycle so we dropped in a pry session in the StaticPagesController and were unable to use the session because of https://github.com/AgileVentures/WebsiteOne/issues/2686 and noticed there aren't any tests for this rake task. 

There seems to be more than one issue here, hence why you said there will need to be changes made to both repos, do you think you could clarify for us the issue? Maybe it will just become really clear when we play around with pry in the rake task, but if you could point us in the right direction, that would be great!

**Comment by tansaku** [comment]
great questions @mattwr18 - I was going to add some documentation on this, but thought I'd start with some executable documentation so I wrote the missing acceptance test for the github static pages import operation.

the lifecycle is that this rake task runs once a day to pull in the *.md pages from AgileVentures/AgileVentures and convert them into the latest version of the static pages in the main site.

So for example the [ABOUT_US.md](https://github.com/AgileVentures/AgileVentures/blob/master/ABOUT_US.md) page in the repo becomes the [about-us](https://www.agileventures.org/about-us) page on the AV site.

This is all well and good.  However unfortunately the various higher premium level pages are hard coded to link to pages with underscores, e.g. premium_mob, premium_f2f etc. and so those pages are still the legacy pages and cannot be edited by updating the corresponding pages on AV/AV (e.g. PREMIUM_MOB.md and PREMIUM_F2F.md).  

In addition the content for those pages in AV/AV is also in an odd state in that we've lost some important formatting that is present in the legacy pages.

As a first step in this repo we should ensure that the md pages have the latest correct content (which might involve having some HTML content).  Once that is done and they have been correctly imported to av.org we could adjust the hard coding of the links in av.org premium subscription pages such that they point to static pages with hypens rather than underscores

As a safety backup we might want the underscore version of the pages to point to the hyphen versions for backwards compatibility ...

Hope that makes more sense ...

**Comment by mattwr18** [comment]
@tansaku I am ready to put in a PR to see what you think about this part of the issue, but I don't have permissions to push to this repo, can you add me to the team?
